### ISSUE TITLE
Can't echo ros2 topics

### ISSUE THREAD

**Issue by MuhamedAgic** [juraph-dev/ros.el#3]
Hello,

I'm relatively new to emacs and i really like this ros package! Unfortunately, i have seen that i cannot echo ros2 topics. I posted and issue here but i doubt that i wil get an answer soon: https://github.com/mbeutelspacher/ros.el/issues/34 

Could you implement this functionality to echo ros2 topics? It would be highly appreciated since i cant program in lisp.

**Comment by juraph-dev** [comment]
G'day! Sorry for the delayed response, I somehow didn't see this come in. 

For sure! I've been meaning to look at it.  I'll get onto that as soon as I can! I'll send another ping once I fix it.

**Comment by MuhamedAgic** [comment]
Hi! mbeutelspacher wrote a fix for it: https://github.com/mbeutelspacher/ros.el/issues/34#issuecomment-2024701829 
Since this repo also contains debug functionality, maybe you can also add this in here?

**Comment by juraph-dev** [comment]
I've merged upstream, and it seems to be working well. Thanks for letting me know, closing.
